[package]
name = "ddc-enhanced-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddc = "0.2.2"
anyhow = "1.0.56"
ddc-hi = "0.4.1"
